#!/usr/bin/env bash

# Create folders in user directory (eg. Documents,Downloads,etc.)
xdg-user-dirs-update
mkdir ~/Screenshots/

# Thunar
sudo apt install -y thunar thunar-archive-plugin thunar-volman file-roller