#!/usr/bin/env bash

cd ~/Downloads

git clone --recursive -b v0.35.0 "https://github.com/hyprwm/Hyprland"
cd Hyprland
make all
sudo make install

sudo mkdir /usr/share/wayland-session
sudo cp ~/debian-hyprland/resources/hyprland.desktop /usr/share/wayland-sessions/

cd ..
rm -rf Hyprland
